#!/bin/bash

# Jenkins Setup Script for dKin Butterfly Club Pipeline
echo "🚀 Jenkins Setup for dKin Butterfly Club Pipeline"
echo "================================================"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}This script will guide you through setting up Jenkins for the complete pipeline.${NC}\n"

echo -e "${GREEN}Step 1: Required Jenkins Plugins${NC}"
echo "Install these plugins via Manage Jenkins > Manage Plugins:"
echo ""
echo "🔧 Core Pipeline Plugins:"
echo "   - Pipeline"
echo "   - Pipeline: Stage View"  
echo "   - Blue Ocean (recommended)"
echo "   - Git"
echo "   - NodeJS"
echo ""
echo "📊 Quality & Security Plugins:"
echo "   - SonarQube Scanner"
echo "   - OWASP Dependency-Check"
echo "   - Checkstyle"
echo "   - JUnit"
echo "   - HTML Publisher"
echo "   - Warnings Next Generation"
echo ""
echo "🚀 Deployment & Monitoring:"
echo "   - SSH Agent"
echo "   - Email Extension Template"
echo "   - Build Monitor View"
echo "   - Timestamper"
echo "   - AnsiColor"
echo ""

echo -e "${GREEN}Step 2: Global Tool Configuration${NC}"
echo "Configure these in Manage Jenkins > Global Tool Configuration:"
echo ""
echo "📦 Node.js:"
echo "   - Name: NodeJS-20"
echo "   - Install automatically: Yes"
echo "   - Version: NodeJS 20.x.x"
echo ""
echo "🔧 Git:"
echo "   - Name: Default"  
echo "   - Path to Git executable: git"
echo ""
echo "🔍 SonarQube Scanner (if using SonarQube):"
echo "   - Name: SonarScanner"
echo "   - Install automatically: Yes"
echo "   - Version: Latest"
echo ""

echo -e "${GREEN}Step 3: System Configuration${NC}"
echo "Configure these in Manage Jenkins > Configure System:"
echo ""
echo "📧 Email Configuration:"
echo "   - SMTP Server: smtp.gmail.com"
echo "   - SMTP Port: 587"
echo "   - Use SMTP Authentication: Yes"
echo "   - Username: your-jenkins-email@gmail.com"
echo "   - Password: [App Password]"
echo ""
echo "🔔 Extended E-mail Notification:"
echo "   - SMTP Server: smtp.gmail.com"  
echo "   - SMTP Port: 587"
echo "   - Default Recipients: your-email@domain.com"
echo ""

echo -e "${GREEN}Step 4: Security Configuration${NC}"
echo ""
echo "🔐 Global Security Settings:"
echo "   - Enable security: Yes"
echo "   - Access Control: Jenkins' own user database"
echo "   - Allow users to sign up: No (recommended for production)"
echo "   - Authorization: Logged-in users can do anything"
echo ""

echo -e "${GREEN}Step 5: Required Credentials${NC}"
echo "Add these in Manage Jenkins > Manage Credentials > (global):"
echo ""

echo "🔑 GitHub Integration:"
echo "   ID: github-token"
echo "   Type: Secret text"
echo "   Secret: [Your GitHub Personal Access Token]"
echo ""

echo "🛡️ Security Scanning:"
echo "   ID: snyk-token" 
echo "   Type: Secret text"
echo "   Secret: [Your Snyk API Token from app.snyk.io]"
echo ""

echo "📊 Code Quality (Optional):"
echo "   ID: sonar-token"
echo "   Type: Secret text" 
echo "   Secret: [Your SonarQube token]"
echo ""

echo "🚀 Deployment:"
echo "   ID: deploy-ssh-key"
echo "   Type: SSH Username with private key"
echo "   Username: deploy"
echo "   Private Key: [Your deployment SSH private key]"
echo ""

echo "📧 Email Notifications:"
echo "   ID: jenkins-email"
echo "   Type: Username with password"
echo "   Username: your-jenkins-email@gmail.com"
echo "   Password: [Gmail App Password]"
echo ""

echo -e "${GREEN}Step 6: Environment Variables${NC}"
echo "Add these environment variables in Manage Jenkins > Configure System > Global Properties:"
echo ""
echo "🌐 Application Variables:"
echo "   JENKINS_URL=http://localhost:8080"
echo "   APP_NAME=dKin-Butterfly-Club"
echo "   NOTIFICATION_EMAIL=your-email@domain.com"
echo ""

echo -e "${YELLOW}Next Steps:${NC}"
echo "1. ✅ Install all required plugins"
echo "2. ✅ Configure global tools"
echo "3. ✅ Setup system configuration"
echo "4. ✅ Add required credentials"
echo "5. ✅ Create pipeline job"
echo ""

echo -e "${BLUE}After setup, run: ./jenkins_create_job.sh${NC}"
echo ""
echo -e "${GREEN}Setup guide complete!${NC}"